### ISSUE TITLE
Спроектировать базу данных

### ISSUE THREAD

**Issue by aleksandr-goncharov** [WhyRocket/sql-practice#4]
Предметная область: Библиотека
Бизнес-требования:

- Требуется хранить информацию о клиентах библиотеки (ФИО, контактные данные), книгах (название, год издания, ISBN), авторах (ФИО, страна), жанрах книг (название) и издателях (название, адрес, контактные данные)
- Клиент может взять одну или несколько книг, если книга взята одним клиентом, она не может быть взята другим
- Каждая книга имеет одного или нескольких авторов
- Каждая книга может относиться к одному или нескольким жанрам
- Каждая книга издана одним издательством

В скобках к каждой сущности приведены атрибуты, которые требуется хранить. По возможности, кол-во атрибутов требуется расширить (возможно, важные атрибуты упущены)

В комментарии к этому ишью требуется спроектировать БД, составив описание сущностей, атрибутов и связей между ними.

Пример проектирования сущностей:
Книги: ID, название, год издания, ISBN, ID издательства (отношение один-ко-многим, много одно Издательство может выпустить много книг)
Жанры книг: ID книги, ID жанра (отношение многие-ко-многим: один жанр может быть у многих книг, у одной книги может быть несколько жанров)

**Comment by WhyRocket** [comment]
Разве ID не излишне? Как понял ISBN это уникальный номер, который мы можем использовать в качестве первичного ключа

**Comment by WhyRocket** [comment]
Книги: 
 - ID [ПЕРВИЧНЫЙ КЛЮЧ] /serial
 - Название /text
 - Год издания /smallint
 - ISBN-13 /character (17)
 - ID издатель /serial
 - Возрастное ограничение /smallserial
 - Количество физических копий /smallserial

Жанр:
 - ID жанра /serial
 - Название жанра /character varying(20)

Жанр_Книг: (Многие-ко-многим)
 - ID книги /serial
 - ID жанра /serial

Клиент:
 - ID [ПЕРВИЧНЫЙ КЛЮЧ] /serial
 - Номер телефона /character (17)
 - Фамилия /character varying(100)
 - Имя /character varying(100)
 - Отчество /character varying(100) [NULLABLE]
 - Дата рождения /date

Клиенты_библиотеки: (Многие-ко-многим)
 - ID клиента
 - ID книги

Издатель: (один-ко-многим) 
 - ID [ПЕРВИЧНЫЙ КЛЮЧ] /serial
 - Название /character varying(100)
 - ID страны /serial
 - Город /character varying(100) 
 - Улица /character varying(100) 
 - Дом /smallint
 - E-mail /character varying(200)
 - Номер телефона для связи /character (17)

Автор:
 - ID [ПЕРВИЧНЫЙ КЛЮЧ] /serial
 - Фамилия /character varying(100)
 - Имя /character varying(100)
 - Отчество /character varying(100) [NULLABLE]
 - ID страны /serial

Автор_Книг: (Многие-ко-многим)
 - ID книги /serial
 - ID автора /serial

Страна: (один-ко-многим)
 - ID страны /serial
 - Страна /character varying(100)
